// <auto-generated />
using System;
using Example_EF_graphql_asp.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example_EF_graphql_asp.NET.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200615020617_initialized-withdata")]
    partial class initializedwithdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Example_EF_graphql_asp.NET.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("678ab5c1-6623-4771-be40-206fc537998e"),
                            Deleted = false,
                            Detail = "something just like this",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("1ab113f3-944a-4705-b592-1c5d3bbfbf97"),
                            Deleted = false,
                            Detail = "something just like this",
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = new Guid("2e87ef0b-33f5-4c1e-9116-72c21a30bfc1"),
                            Deleted = false,
                            Detail = "OMG",
                            Name = "Mike Miles"
                        });
                });

            modelBuilder.Entity("Example_EF_graphql_asp.NET.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Example_EF_graphql_asp.NET.Models.Product", b =>
                {
                    b.HasOne("Example_EF_graphql_asp.NET.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
